module.exports = {
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  COMMENTS_RECEIVED: "COMMENTS_RECEIVED",
  COMMENT_CREATED: "COMMENT_CREATED",
  COMMENT_DELETED: "COMMENT_DELETED",


  FRIEND_RECEIVED: "FRIEND_RECEIVED",
  FRIENDS_RECEIVED: "FRIENDS_RECEIVED",
  FRIEND_CREATED: "FRIEND_CREATED",
  FRIEND_DELETED: "FRIEND_DELETED",

  PHOTO_RECEIVED: "PHOTO_RECEIVED",
  PHOTOS_RECEIVED: "PHOTOS_RECEIVED",
  PHOTO_CREATED: "PHOTO_CREATED",
  PHOTO_DELETED: "PHOTO_DELETED",
  PHOTO_UPDATED: "PHOTO_UPDATED",


  POST_RECEIVED: "POST_RECEIVED",
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_CREATED: "POST_CREATED",
  POST_DELETED: "POST_DELETED",


  RESULTS_RECEIVED: "RESULTS_RECEIVED",


  USER_RECEIVED: "USER_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_CREATED: "USER_CREATED",
  USER_DELETED: "USER_DELETED",



  TIMELINE_RECEIVED: "TIMELINE_RECEIVED",

  PROFILE_RECEIVED: "PROFILE_RECEIVED",



  REMOVE_FRIEND: "REMOVE_FRIEND",
}
