module.exports = {
  LIKES_RECEIVED: "LIKES_RECEIVED",
  LIKE_DELETED: "LIKE_DELETED",
  LIKE_UPDATED: "LIKE_UPDATED",
  TIMELINE_LIKE_DELETED: "TIMELINE_LIKE_DELETED",
  TIMELINE_LIKE_UPDATED: "TIMELINE_LIKE_UPDATED",
}
